// ================================================================
// S6  MOVE LEGALITY VALIDATION
// ================================================================
//
//   isLegal(p, move) answers: "could this move string have been
//   generated by genCaptures / genQuiet for the current position?"
//
//   WHY DO WE NEED THIS?
//   --------------------
//   The transposition table and killer-move tables can hold moves from
//   different positions.  Before trying one of those stored moves we
//   must verify it is legal in the current position to avoid crashes
//   or corrupted search results.
//
//   The check is intentionally lightweight: we validate the move
//   structure and the piece on the from-square, but we do NOT make
//   the move and test for discovered check.  That is handled by
//   selfInCheck() in the main search loop after makeMove().
//
//   LEGALITY RULES SUMMARY
//   ----------------------
//   1. A piece of the moving side must exist on fromSq.
//   2. If there is a piece on toSq, it must belong to the opponent.
//   3. The move type must match the actual position:
//      CASTLE: castling rights must be intact, path must be clear,
//              king and transit square must not be attacked.
//      EP_CAP: toSq must equal the current en-passant square.
//      EP_SET: pawn must be making a true double push to an empty sq.
//   4. For NORMAL/PROM moves on pawns: direction, rank, and capture
//      status must be consistent with the piece colour.
//   5. For non-pawn pieces: toSq must be reachable via attacksFrom.
//

package main

// isLegal returns true if move is a legal move for the side to move
// in position p.  It does NOT check for self-check (the caller does
// that via selfInCheck after makeMove).
func isLegal(p *Pos, move int) bool {
	side := p.side
	from := moveFrom(move)
	to := moveTo(move)
	fromType := p.typeAt(from)
	toType := p.typeAt(to)

	// The from-square must hold a piece belonging to the moving side.
	if fromType == NO_TP || colorOf(p.board[from]) != side {
		return false
	}
	// The to-square must be empty or hold an enemy piece (unless castling in FRC, where king takes friendly rook).
	if moveType(move) != CASTLE {
		if toType != NO_TP && colorOf(p.board[to]) == side {
			return false
		}
	}

	switch moveType(move) {
	case NORMAL:
		// Fall through to piece-specific checks below.

	case CASTLE:
		// In FRC, from is kingSq and to is rookSq.
		if from != p.kingSq[side] {
			return false
		}
		
		var kingDst, rookDst int
		var isKingside bool
		
		if side == White {
			isKingside = (to == p.castlingRookSq[White][0])
			if isKingside {
				if p.castleRights&wKingsideCastle == 0 { return false }
				kingDst = G1
				rookDst = F1
			} else if to == p.castlingRookSq[White][1] {
				if p.castleRights&wQueensideCastle == 0 { return false }
				kingDst = C1
				rookDst = D1
			} else {
				return false
			}
		} else {
			isKingside = (to == p.castlingRookSq[Black][0])
			if isKingside {
				if p.castleRights&bKingsideCastle == 0 { return false }
				kingDst = G8
				rookDst = F8
			} else if to == p.castlingRookSq[Black][1] {
				if p.castleRights&bQueensideCastle == 0 { return false }
				kingDst = C8
				rookDst = D8
			} else {
				return false
			}
		}
		
		castleOcc := p.occupied() &^ (squareBit(from) | squareBit(to))
		clearMask := BetweenBB[from][kingDst] | BetweenBB[from][to] | squareBit(kingDst) | squareBit(rookDst)
		if castleOcc&clearMask != 0 {
			return false
		}
		
		checkMask := BetweenBB[from][kingDst] | squareBit(kingDst) | squareBit(from)
		bb := checkMask
		for bb != 0 {
			sq := lsb(bb)
			if isAttacked(p, sq, opp(side)) {
				return false
			}
			bb &= bb - 1
		}
		return true

	case EP_CAP:
		return fromType == P && to == p.epSquare

	case EP_SET:
		// Double push: pawn must move two ranks forward into an empty
		// square, and the square it jumped over must also be empty.
		return fromType == P && toType == NO_TP && p.board[to^8] == NO_PC &&
			((to > from && side == White) || (to < from && side == Black))
	}

	// --- Pawn-specific checks for NORMAL and promotion moves ---
	if fromType == P {
		if side == White {
			// A White pawn on rank 7 must promote; a non-promotion here is illegal.
			if rankOf(from) == 7 && !isProm(move) {
				return false
			}
			// Straight push: must land on an empty square.
			if to-from == 8 {
				return toType == NO_TP
			}
			// Diagonal capture: must land on an enemy piece.
			if (to-from == 7 && fileOf(from) != 0) || (to-from == 9 && fileOf(from) != 7) {
				return toType != NO_TP
			}
		} else {
			if rankOf(from) == 0 && !isProm(move) {
				return false
			}
			if from-to == 8 {
				return toType == NO_TP
			}
			if (from-to == 7 && fileOf(from) != 7) || (from-to == 9 && fileOf(from) != 0) {
				return toType != NO_TP
			}
		}
		return false
	}

	// Non-pawn pieces must not carry a promotion flag.
	if isProm(move) {
		return false
	}

	// The piece must be able to reach the target square.
	return attacksFrom(p, from)&squareBit(to) != 0
}
